# Install requirements via apt....
sudo apt update ## Update repo info....
sudo apt install -y flatpak wget curl python3 python3-pip ## requirements via apt....

# Uninstall the "politically heated" firefox, thunderbird, and "stale" libreoffice... we will replace these later! ;)
sudo apt remove -y firefox ## Checks for the apt package...
sudo snap remove firefox ## Checks for the snap package...
sudo apt remove -y thunderbird ## Checks for the apt package...
sudo snap remove thunderbird ## Checks for the snap package...
sudo apt remove -y libreoffice* ## Checks for the apt package...
sudo snap remove libreoffice* ## Checks for the snap package... (for the future.)

# Update any existing flatpaks...
flatpak update ## update em all....

# Add flathub repo...
flatpak remote-add -y --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo ## the hub ;)

# Install coding stuffs...
flatpak install -y org.filezillaproject.Filezilla # FTP/SFTP uploading program
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash # nvm, used to manage nodejs versions

# SneedHosts (Got permission from the Sneed Group team to use this!)
printf "# SneedHosts Collection. Made by Sneed Group.\n" > sneedhosts.tmp ## Init the hosts with a line giving credit.
curl https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/pro.txt >> sneedhosts.tmp ## Get collection
printf "\n" >> sneedhosts.tmp ## New line
curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts >> sneedhosts.tmp ## Get collection
printf "\n" >> sneedhosts.tmp ## New line
curl https://someonewhocares.org/hosts/hosts >> sneedhosts.tmp ## Get collection
printf "\n # END OF SNEEDHOSTS" >> sneedhosts.tmp ## End Of File
sudo mv /etc/hosts /etc/hosts.bak ## Backup old hosts file...
sudo cp sneedhosts.tmp /etc/hosts ## ...and insert ours instead!

# Clear and ask for reboot.
clear ## Clear the screen.
echo "Done! PLEASE REBOOT NOW TO APPLY CHANGES." ## Asks for reboot.
